# cloudbuild.yaml
substitutions:
  _PROJECT_ID: "rich-world-473106-v3"
  _REGION: "us-central1"
  _ARTIFACT_REPO: "app-images"
  _GKE_CLUSTER: "pubsub-trace-cluster"
  _GKE_ZONE: "us-central1-c"
  _K8S_NAMESPACE: "pubsub-trace"

steps:
# 1) Build backend-a
- id: "build-backend-a"
  name: "gcr.io/buildpacks/builder:v1"
  args: ["pack", "build", "us-central1-docker.pkg.dev/${_PROJECT_ID}/${_ARTIFACT_REPO}/backend-a:$SHORT_SHA", "--path", "backend-a"]
  waitFor: ["-"]

# 2) Build backend-b
- id: "build-backend-b"
  name: "gcr.io/buildpacks/builder:v1"
  args: ["pack", "build", "us-central1-docker.pkg.dev/${_PROJECT_ID}/${_ARTIFACT_REPO}/backend-b:$SHORT_SHA", "--path", "backend-b"]
  waitFor: ["build-backend-a"]

# 3) Build frontend (static)
- id: "build-frontend"
  name: "gcr.io/buildpacks/builder:v1"
  args: ["pack", "build", "us-central1-docker.pkg.dev/${_PROJECT_ID}/${_ARTIFACT_REPO}/frontend:$SHORT_SHA", "--path", "frontend"]
  waitFor: ["build-backend-b"]

# 4) Configure kubectl (use gcloud)
- id: "kubectl-setup"
  name: "gcr.io/google.com/cloudsdktool/cloud-sdk:slim"
  entrypoint: bash
  args:
    - -c
    - |
      gcloud config set project ${_PROJECT_ID}
      gcloud container clusters get-credentials ${_GKE_CLUSTER} --zone ${_GKE_ZONE} --project ${_PROJECT_ID}

# 5) Deploy: replace images in k8s manifests and apply
- id: "kubectl-deploy"
  name: "gcr.io/google.com/cloudsdktool/cloud-sdk:slim"
  entrypoint: bash
  args:
    - -c
    - |
      # substitute image references in YAML then apply
      sed -e "s|IMAGE_BACKEND_A|us-central1-docker.pkg.dev/${_PROJECT_ID}/${_ARTIFACT_REPO}/backend-a:${SHORT_SHA}|g" \
          -e "s|IMAGE_BACKEND_B|us-central1-docker.pkg.dev/${_PROJECT_ID}/${_ARTIFACT_REPO}/backend-b:${SHORT_SHA}|g" \
          -e "s|IMAGE_FRONTEND|us-central1-docker.pkg.dev/${_PROJECT_ID}/${_ARTIFACT_REPO}/frontend:${SHORT_SHA}|g" \
          k8s/backend-a-deployment.yaml k8s/backend-b-deployment.yaml k8s/frontend-deployment.yaml > /tmp/k8s-manifests.yaml
      kubectl apply -f /tmp/k8s-manifests.yaml
  waitFor: ["kubectl-setup"]

images:
- "us-central1-docker.pkg.dev/${_PROJECT_ID}/${_ARTIFACT_REPO}/backend-a:${SHORT_SHA}"
- "us-central1-docker.pkg.dev/${_PROJECT_ID}/${_ARTIFACT_REPO}/backend-b:${SHORT_SHA}"
- "us-central1-docker.pkg.dev/${_PROJECT_ID}/${_ARTIFACT_REPO}/frontend:${SHORT_SHA}"